export {default as Logo} from './assets/SVGs/Logo.jsx'
export {default as Theme} from './assets/SVGs/Theme.jsx'
export {default as Sun} from './assets/SVGs/Sun.jsx'
export {default as Temp} from './assets/SVGs/Temp.jsx'
export {default as Humidity} from './assets/SVGs/Humidity.jsx'
export {default as Wind} from './assets/SVGs/Wind.jsx'
export {default as Precipitation} from './assets/SVGs/Precipitation.jsx'